In [27]:
import numpy as np
import pickle 
import pandas as pd
# import numpy as np
import random

In [50]:
a = pd.read_pickle('./first_experiment/Realization_list.pkl')

In [51]:
a

{10: [[array([1., 0., 0., 0., 0., 1., 1., 1., 1., 1.]),
   array([1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]),
   array([1., 1., 1., 0., 1., 1., 0., 1., 1., 0.]),
   array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
   array([1., 1., 0., 1., 0., 0., 1., 1., 1., 1.]),
   array([1., 1., 0., 1., 1., 1., 0., 1., 1., 0.]),
   array([1., 1., 1., 1., 1., 1., 1., 0., 1., 1.]),
   array([0., 1., 1., 1., 0., 0., 1., 0., 0., 1.]),
   array([0., 1., 0., 1., 1., 0., 1., 0., 1., 0.]),
   array([1., 0., 1., 1., 1., 1., 1., 0., 1., 1.]),
   array([1., 1., 1., 1., 1., 0., 1., 1., 1., 1.]),
   array([1., 1., 1., 1., 1., 1., 1., 0., 0., 0.]),
   array([1., 1., 1., 1., 0., 1., 1., 1., 1., 1.]),
   array([1., 0., 1., 1., 0., 1., 0., 0., 0., 1.]),
   array([0., 1., 1., 1., 0., 0., 1., 1., 0., 1.]),
   array([1., 1., 1., 1., 0., 1., 0., 1., 0., 1.]),
   array([1., 0., 1., 1., 1., 1., 0., 1., 1., 1.]),
   array([1., 0., 1., 1., 1., 1., 1., 1., 1., 0.]),
   array([1., 1., 0., 1., 1., 1., 1., 0., 1., 1.]),
   array

In [52]:
b= pd.read_pickle('./second_experiment/Realization_list2.pkl')


In [56]:
N  = [10,15,20]

for n in N:
    for j in range(6,10):
        real_file_name = f'./homogeneous/realization_{n}_{j}.pickle'

        demand = a[n][j-5]
        with open(real_file_name, 'wb') as f:
            pickle.dump(demand, f)



In [ ]:
import numpy as np
import random

def build_instance(nb_demands,ROI,nb_ceneters):
    n = nb_demands
    Demand = dict()
    Demand['x'] = np.zeros(n)
    Demand['y'] = np.zeros(n)
    Demand['width'] = np.zeros(n)
    Demand['height'] = np.zeros(n)
    Demand['reward'] = np.zeros(n)

    ######################################################
    center_point = {}
    center_point['x'] = np.zeros(nb_ceneters)
    center_point['y'] = np.zeros(nb_ceneters)

    # center_point['x'][0] = random.randint(-400, -150)
    # center_point['x'][1] =random.randint(-100, 100)
    # center_point['x'][2] = random.randint(150,400)

    center_point['x'][0] = random.randint(0, 250)
    center_point['x'][1] =random.randint(300, 500)
    center_point['x'][2] = random.randint(550,800)

    # center_point['y'][0] = random.randint(-250,-150)
    # center_point['y'][1] = random.randint(-100,100)
    # center_point['y'][2] = random.randint(-250,-150)

    center_point['y'][0] = random.randint(0,100)
    center_point['y'][1] = random.randint(150,350)
    center_point['y'][2] = random.randint(0,100)
    # center_point['x']= [random.randint(30, 110) for i in range(nb_ceneters)]
    # center_point['y']= [random.randint(30, 110) for i in range(nb_ceneters)]

    Demand['width'] = [random.randint(5, 50) for i in range(n)] # demands width follows uniform(5,50)
    Demand['height'] = [random.randint(5, 50) for i in range(n)] # demands height follows uniform(5,50)
    Demand['reward'] = [random.randint(1, 10) for i in range(n)]  # demands reward follows uniform(5,50)

    Demand['x'][0:int(n*0.31)] = np.random.normal(center_point['x'][0], ROI / 3, int(n*0.31))
    Demand['y'][0:int(n*0.31)] = np.random.normal(center_point['y'][0], ROI / 3, int(n*0.31))

    Demand['x'][int(n*0.31):int(n*0.62)] = np.random.normal(center_point['x'][1], ROI / 3, int(n*0.62) - int(n*0.31))
    Demand['y'][int(n*0.31):int(n*0.62)] = np.random.normal(center_point['y'][1], ROI / 3, int(n*0.62) - int(n*0.31))

    Demand['x'][int(n*0.62):int(n*0.93)] = np.random.normal(center_point['x'][2], ROI / 3, int(n*0.93) - int(n*0.62))
    Demand['y'][int(n*0.62):int(n*0.93)] = np.random.normal(center_point['y'][2], ROI / 3, int(n*0.93) - int(n*0.62))

    Demand['x'][int(n*0.93):n] = np.random.uniform(10,70, n - int(n*0.93))
    Demand['y'][int(n*0.93):n] = np.random.uniform(10,70, n - int(n*0.93))

    Demand['x'] = Demand['x'].tolist()
    Demand['y'] = Demand['y'].tolist()
    
    
    return Demand

# M-CFP-F

In [21]:
import numpy as np
import random


def build_instance(nb_demands, ROI, nb_ceneters):
    n = nb_demands
    Demand = dict()
    Demand['x'] = np.zeros(n)
    #     Demand['y'] = np.zeros(n)
    Demand['width'] = np.zeros(n)
    #     Demand['height'] = np.zeros(n)
    Demand['reward'] = np.zeros(n)
    Demand['desired'] = np.zeros(n)

    ######################################################
    center_point = {}
    center_point['x'] = np.zeros(nb_ceneters)

    center_point['x'][0] = random.randint(0, 20)
    center_point['x'][1] = random.randint(0, 30)
    center_point['x'][2] = random.randint(0, 40)

    Demand['width'] = [random.randint(20, 40) for i in range(n)]  # demands width follows uniform(5,50)
    #     Demand['height'] = [random.randint(5, 50) for i in range(n)] # demands height follows uniform(5,50)
    Demand['reward'] = [random.randint(1, 30) for i in range(n)]  # demands reward follows uniform(5,50)
    #     Demand['desired'] = [random.randint(30, 50) for i in range(n)]
    Demand['desired'] = [1 for i in range(n)]
    Demand['x'][0:int(n * 0.31)] = np.random.normal(center_point['x'][0], ROI / 3, int(n * 0.31))
    #     Demand['y'][0:int(n*0.31)] = np.random.normal(center_point['y'][0], ROI / 3, int(n*0.31))

    Demand['x'][int(n * 0.31):int(n * 0.62)] = np.random.normal(center_point['x'][1], ROI / 3,
                                                                int(n * 0.62) - int(n * 0.31))
    #     Demand['y'][int(n*0.31):int(n*0.62)] = np.random.normal(center_point['y'][1], ROI / 3, int(n*0.62) - int(n*0.31))

    Demand['x'][int(n * 0.62):int(n * 0.93)] = np.random.normal(center_point['x'][2], ROI / 3,
                                                                int(n * 0.93) - int(n * 0.62))
    #     Demand['y'][int(n*0.62):int(n*0.93)] = np.random.normal(center_point['y'][2], ROI / 3, int(n*0.93) - int(n*0.62))

    Demand['x'][int(n * 0.93):n] = np.random.uniform(10, 70, n - int(n * 0.93))
    #     Demand['y'][int(n*0.93):n] = np.random.uniform(10,70, n - int(n*0.93))

    Demand['x'] = Demand['x'].tolist()
    #     Demand['y'] = Demand['y'].tolist()

    return Demand

In [25]:
N = [10,20,50]


ROI = 270
nb_center = 3

# for i in r

for n in N:
    for j in range(10):
        real_file_name = f'./M-CFP-F/demand_{n}_{j}.pickle'

        Demand = build_instance(n,ROI,nb_center)
        with open(real_file_name, 'wb') as f:
            pickle.dump(Demand, f)

# with open ()

In [ ]:
real_file_name = f'{reali_folder}/realization_{self.file_name}.pickle'
with open(real_file_name, 'wb') as f:
    pickle.dump(self.data.realization, f)